//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord1 v2
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_texcoord1 o2.xyz
    mov o0, v0
    mov o1.xy, v1
    mov o2.xyz, v2

// approximately 3 instruction slots used
